### ISSUE TITLE
 Stop-TogglEntry  is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by arnelap** [Clijsters/PSToggl#4]
Stop-TogglEntry : The term 'Stop-TogglEntry' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Stop-TogglEntry
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Stop-TogglEntry:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by clijsters** [comment]
Thank you for submitting that issue. That is a documentation issue, because the code example lists a cmdlet which doesn't exist yet. 

But yeah it is crucial to be able to stop a running timer for a full functioning Toggl Client. 
I will implement this as fast as possible. Until then it's up-for-grabs!

**Comment by clijsters** [comment]
Status Update: Tests are finished and expecting something like:

    $runningEntry = (Get-TogglEntry -Current)
    if ($runningEntry) {
        $answer = Invoke-TogglMethod -UrlSuffix ("time_entries/" + $runningTimer.id + "/stop")
        Write-Output $answer
    }

(What layed in my profile functions for months. That's why I didn't realized that this feature wasn't implemented.)

Plus Workspace management (Getting implemented in #7 and [Private task "Alle public cmdlets brauchen den Workspace Parameter"](https://www.meistertask.com/app/task/g3bUNm4p/alle-public-cmdlets-brauchen-den-workspace-parameter))
And some nice pipeline support and documentation updates.
